spring:
  application:
    name: activiti
  datasource:
    url: jdbc:mysql://localhost:3306/activiti?characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080